### PR TITLE
Add action confirmation modal

### PR DESCRIPTION
**Pull request by selankon**
Fix https://github.com/vocdoni/ui-components/issues/156

image

### CODE REVIEW

**Review by elboletaire — CHANGES_REQUESTED** [review]
I think this needs a "cancel" button to be more clear. I know it can be closed either with the close button, clicking outside or even with the <kbd>Esc</kbd> key, but I feel like it's required.

Other than that, code LGTM

**Comment by jpaulet** [comment]
Also, the CTA model should explain the action. Instead of "Confirm" change to "End Voting" or "Cancel process".

**Review by jpaulet — APPROVED** [review]
Reviewed and ready to merge

**Review by jpaulet — DISMISSED** [review]
Apply first the requested changes.

**Comment by elboletaire** [comment]
> Also, the CTA model should explain the action. Instead of "Confirm" change to "End Voting" or "Cancel process".

Totally agree.

**Comment by selankon** [comment]
This will fix the cta button text ed410c7

But for the other requested change, the cancel button, I added translations here: ca3aa44

But the cancel button is disabled at ui-scaffold level, so we have to think how we have to fix it https://github.com/vocdoni/ui-scaffold/blob/refs/heads/develop/src/themes/default/components/ConfirmModal.ts#L19-L21

**Pull request merged**
